### ISSUE TITLE
mastercomfig MIT license

### ISSUE THREAD

**Issue by mastercoms** [micwoj92/broconfig#1]
This repo contains assets from mastercomfig, but does not follow the attribution requirement within the MIT license in the mastercomfig repo. Please fix this, such that broconfig includes the copyright notice for mastercomfig within its own license.

**Comment by micwoj92** [comment]
Is adding 2 newlines with `
mastercomfig
Copyright (c) 2016-2020 mastercoms`
the right solution?

**Comment by micwoj92** [comment]
Is adding:

mastercomfig

Copyright (c) 2016-2020 mastercoms

to the license right solution?

**Comment by mastercoms** [comment]
`Copyright (c) 2016-2020 mastercoms` under Copyright (c) 2020 micwoj92

**Comment by micwoj92** [comment]
Added https://github.com/micwoj92/broconfig/commit/ee49d49255ecfce503d9187e3f8652294bfeb4e9
Thanks
